FSTAR=fstar.exe

all : stlc stlc-ints stlc-letrec stlc-sub

stlc : stlc.fst
	$(FSTAR) $^

stlc-ints: stlc-ints.fst
	$(FSTAR) $^

stlc-letrec: stlc-letrec.fst
	$(FSTAR) $^

stlc-sub: stlc-sub.fst
	$(FSTAR) $^
